name: untitled13
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  fl_chart: ^0.63.0
  firebase_core: ^2.30.0
  cloud_firestore: ^4.17.0
  firebase_auth: ^4.17.4
  http: ^0.13.6
  audioplayers: ^5.2.1
  video_player: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icons"
  ios: true
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/bg.jpg
    - assets/bg1.jpg
    - assets/bg2.jpg
    - assets/bg3.jpg
    - assets/bg4.jpg
    - assets/heart.png
    - assets/meditation.mp3
    - assets/meditation.mp4
    - assets/trvl.jpg
    - assets/stones.jpg
    - assets/planet.jpg
    - assets/galaxy.jpg
    - assets/lscp.jpg
    - assets/icon.png
    - assets/signup.jpg
    - assets/bac1.jpg
    - assets/habit.jpg
