// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQ2zryZBn8VazxQ9R3URq88A0x2qxn364',
    appId: '1:645629388800:web:5339dbace48be2b68310e5',
    messagingSenderId: '645629388800',
    projectId: 'mental-health-app-14039',
    authDomain: 'mental-health-app-14039.firebaseapp.com',
    storageBucket: 'mental-health-app-14039.firebasestorage.app',
    measurementId: 'G-VK232C39GQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcgs3sUQoM8QzlzHqfYp9HtRcUQTjziZs',
    appId: '1:645629388800:android:6cc23343e74b8b158310e5',
    messagingSenderId: '645629388800',
    projectId: 'mental-health-app-14039',
    storageBucket: 'mental-health-app-14039.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBf5xpvu6jCUeXRDp3IqXVA9-xJBDScGqo',
    appId: '1:645629388800:ios:9d80b20422a8ac368310e5',
    messagingSenderId: '645629388800',
    projectId: 'mental-health-app-14039',
    storageBucket: 'mental-health-app-14039.firebasestorage.app',
    iosBundleId: 'com.example.untitled13',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBf5xpvu6jCUeXRDp3IqXVA9-xJBDScGqo',
    appId: '1:645629388800:ios:9d80b20422a8ac368310e5',
    messagingSenderId: '645629388800',
    projectId: 'mental-health-app-14039',
    storageBucket: 'mental-health-app-14039.firebasestorage.app',
    iosBundleId: 'com.example.untitled13',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQ2zryZBn8VazxQ9R3URq88A0x2qxn364',
    appId: '1:645629388800:web:0f225ba0b8ae082a8310e5',
    messagingSenderId: '645629388800',
    projectId: 'mental-health-app-14039',
    authDomain: 'mental-health-app-14039.firebaseapp.com',
    storageBucket: 'mental-health-app-14039.firebasestorage.app',
    measurementId: 'G-CZES31LY4C',
  );
}
